# Generated by Django 3.2.6 on 2021-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_ans', models.CharField(max_length=20)),
                ('S_ans', models.CharField(max_length=20)),
                ('T_ans', models.CharField(max_length=20)),
                ('J_ans', models.CharField(max_length=20)),
                ('E_value', models.CharField(max_length=20)),
                ('S_value', models.CharField(max_length=20)),
                ('T_value', models.CharField(max_length=20)),
                ('J_value', models.CharField(max_length=20)),
                ('Personality_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.IntegerField()),
                ('questionPage', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('answer0', models.CharField(max_length=500)),
                ('answer1', models.CharField(max_length=500)),
            ],
        ),
    ]
