# Generated by Django 3.2.6 on 2021-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210903_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patnertbio',
            name='education',
            field=models.CharField(choices=[('ol', 'O/L'), ('al', 'A/L'), ('diploma', 'Diploma'), ('Bachdeg', "Bachelor's degree"), ('Mastdeg', "Master's degree"), ('phd', 'Phd')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patnertbio',
            name='eye_color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('blue', 'Blue'), ('gray', 'Gray'), ('hazel', 'Hazel')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patnertbio',
            name='nationality',
            field=models.CharField(choices=[('sinhala', 'Sinhala'), ('tamil', 'Tamil'), ('muslim', 'Muslim'), ('other', 'Other')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patnertbio',
            name='occupation',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patnertbio',
            name='religion',
            field=models.CharField(choices=[('buddhism', 'Buddhism'), ('christian', 'Christian'), ('hindu', 'Hindu'), ('islam', 'Islam'), ('other', 'Other')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patnertbio',
            name='skin_complexity',
            field=models.CharField(choices=[('very_dark', 'Very dark'), ('dark_brown', 'Dark brown'), ('mid_brown', 'Mid brown'), ('medium', 'Medium'), ('fair', 'Fair'), ('light', 'Light')], default=None, max_length=50),
        ),
    ]
