# Generated by Django 3.2.6 on 2021-10-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_matchingcouples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingcouples',
            name='patner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchingcouples',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
